### ISSUE TITLE
Bad Footprint Pinout

### ISSUE THREAD

**Issue by andrewpable** [chicagoedt/gEDA_Footprints#3]
When I try to convert a schematic to a layout the pinout of the footprint gets completely jumbled around, and there seems to be no solution.

**Comment by sabinoj** [comment]
I was looking into the actual text file that makes up the footprint and it appears that the netlist of the footprint can be modified. Here's an example of my USB_Micro (something like that) footprint from the USB folder.


http://pastebin.com/vPD7JVC9

 Here is a breakdown of the footprint.

**Pad[0 -11811 0 -8661 1969 1200 2569 "3" "1" "square"]**

Pad           <- This identifies that it is a Surface Mount pad (I think).
"3"            <- This is the label/name of the pad.
"1"            <- This is the PinName.
"square"   <- I think this identifies the size of the pad (not sure).

**Comment by sabinoj** [comment]
I just tried changing the second double quoted number (the "1" in the above example) and it did appear to correct the entire issue.

**Comment by andrewpable** [comment]
Tested this as well and it works for me.
