### ISSUE TITLE
TDK CC3E Error

### ISSUE THREAD

**Issue by sabinoj** [chicagoedt/gEDA_Footprints#9]
@andrewpable The CC3E footprint for the TDK switching regulator appears to be backwards, would you be able to take a look as well and see if you can correct it? 

Matt, Jon, and myself will be reviewing several things tonight at the shop.

**Comment by andrewpable** [comment]
Uh hey John the footprint and the symbol are exactly pinned out as
specified in the data sheet attached. If your problem is when you are
importing the schematic, remember it was goofy but not backwards, you had
me do something to fix but I can't remember what again.

**Comment by sabinoj** [comment]
@andrewpable I was trying to add the switching regulator to my senior design project and the pad is upside-down.

**Comment by andrewpable** [comment]
Hmm. It looks fine on my PC let's talk at EDT, I'll be in around 530

**Comment by sabinoj** [comment]
@andrewpable 
The footprint in gEDA is fine, the issue is that when used to physically place the switching regulator on the board it does not fit unless you were able to somehow, magically, place the regulator upside-down. I'm not saying that you did it wrong, just that the data sheet may have been wrong.

From my experience with TDK in the past, I would not be surprised if the data sheet footprint was based on the guy picking up the switching regulator and looking at it upside-down and not in reference to it on a circuit board.

**Comment by sabinoj** [comment]
I will be in tonight starting around 5:00PM, so if you want to stop in and talk about it, feel free.

**Comment by sabinoj** [comment]
Here is the data sheet for it:
http://www.tdk-lambda.com/products/sps/catalog/eng/cc_e.pdf

**Comment by andrewpable** [comment]
hey, so the datasheet has 2 different views of it and I'm not so sure, do
you think you could come by the shop and help me out

**Comment by sabinoj** [comment]
The issue has been resolved.
